# yaml-language-server: $schema=https://www.flowlauncher.com/schemas/settings-template.schema.json
body:
  - type: textarea
    attributes:
      name: program_path
      label: Program Path
      description: >
        Configure application paths in the following format:
        
        APP_DOWNLOAD=C:/path/to/app.exe
        
        APP_STORAGE=C:/path/to/storage/file

        Each application needs both DOWNLOAD and STORAGE entries.
      defaultValue: ""
