# yaml-language-server: $schema=https://www.flowlauncher.com/schemas/settings-template.schema.json
body:
  - type: textarea
    attributes:
      name: program_path
      label: Program Path
      description: >
        Configure application paths in the following format:
        
        APP_DOWNLOAD=C:/path/to/app.exe
        
        APP_STORAGE=C:/path/to/storage/file

        Each application needs both DOWNLOAD and STORAGE entries.
      defaultValue: ""
  - type: textarea
    attributes:
      name: suggestions_list
      label: Suggestions List
      description: >
        Configure list of program suggestions in the following format:

        VSCODE

        PYCHARM

        INTELLIJ_IDEA

        It will be displayed when the plugin is activated.

        Keep empty to display the default program suggestions.
  - type: input
  - type: input
    attributes:
      name: plugin_trigger_keyword
      label: Plugin Trigger Keyword
      description: >
        The keyword to trigger the plugin.

        If you change it, please update here as well.
      defaultValue: "r"
  - type: textarea
    attributes:
      name: custom_acronyms_map
      label: Custom Acronyms Map
      description: >
        Configure custom acronyms for your programs in the following format:

        VSCODE=vsc

        PYCHARM=py

        Each line defines a mapping from the program name to its acronyms.
      defaultValue: ""


