body:
  - type: textBlock
    attributes:
      description: Please enter the corresponding path
  - type: input
    attributes:
      name: VISUAL_STUDIO_CODE_DOWNLOAD
      label: VISUAL_STUDIO_CODE_DOWNLOAD
      description: Please enter the download location of VISUAL_STUDIO_CODE
      defaultValue: 
  - type: input
    attributes:
      name: VISUAL_STUDIO_CODE_STORAGE
      label: VISUAL_STUDIO_CODE_STORAGE
      description: Please enter the STORAGE location of VISUAL_STUDIO_CODE
      defaultValue:
  - type: input
    attributes:
      name: ANDROID_STUDIO_DOWNLOAD
      label: ANDROID_STUDIO_DOWNLOAD
      description: Please enter the download location of ANDROID_STUDIO
      defaultValue:
  - type: input
    attributes:
      name: ANDROID_STUDIO_STORAGE
      label: ANDROID_STUDIO_STORAGE
      description: Please enter the STORAGE location of ANDROID_STUDIO
      defaultValue:
  - type: input
    attributes:
      name: INTELLIJ_IDEA_DOWNLOAD
      label: INTELLIJ_IDEA_DOWNLOAD
      description: Please enter the download location of INTELLIJ_IDEA
      defaultValue:
  - type: input
    attributes:
      name: INTELLIJ_IDEA_STORAGE
      label: INTELLIJ_IDEA_STORAGE
      description: Please enter the STORAGE location of INTELLIJ_IDEA
      defaultValue:
  - type: input
    attributes:
      name: PYCHARM_DOWNLOAD
      label: PYCHARM_DOWNLOAD
      description: Please enter the download location of PYCHARM
      defaultValue:
  - type: input
    attributes:
      name: PYCHARM_STORAGE
      label: PYCHARM_STORAGE
      description: Please enter the STORAGE location of PYCHARM
      defaultValue:
  - type: input
    attributes:
      name: GOLAND_DOWNLOAD
      label: GOLAND_DOWNLOAD
      description: Please enter the download location of GOLAND
      defaultValue:
  - type: input
    attributes:
      name: GOLAND_STORAGE
      label: GOLAND_STORAGE
      description: Please enter the STORAGE location of GOLAND
      defaultValue:
  - type: input
    attributes:
      name: CLION_DOWNLOAD
      label: CLION_DOWNLOAD
      description: Please enter the download location of CLION
      defaultValue:
  - type: input
    attributes:
      name: CLION_STORAGE
      label: CLION_STORAGE
      description: Please enter the STORAGE location of CLION
      defaultValue:
